version: 0.2
env:
  variables:
    BUILD_ENV: prod

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm ci
  pre_build:
    on-failure: ABORT
    commands:
      - echo Linting project...
      - npm run lint
      - echo Testing project...
      - npm test
  build:
    commands:
      - echo Building project...
      - npm run build --${BUILD_ENV}
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - dist/**/*
